- name: Deploy Prometheus and Grafana on Worker1
  hosts: master
  become: yes
  tasks:
    - name: Add Prometheus Helm repository
      command: /usr/local/bin/helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: /usr/local/bin/helm repo update

    - name: Create monitoring namespace
      command: kubectl create namespace monitoring
      ignore_errors: yes

    - name: Create custom values.yaml for nodeSelector
      copy:
        dest: /tmp/prometheus_values.yaml
        content: |
          nodeSelector:
            kubernetes.io/hostname: "worker1"

          alertmanager:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: "worker1"

          grafana:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: "worker1"

          prometheus:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: "worker1"

          prometheusOperator:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: "worker1"

          kubeStateMetrics:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: "worker1"

          nodeExporter:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: "worker1"

    - name: Install Prometheus & Grafana on Worker1
      command: >
        /usr/local/bin/helm upgrade --install prometheus prometheus-community/kube-prometheus-stack
        --namespace monitoring
        --values /tmp/prometheus_values.yaml
