---
- name: Deploy Prometheus and Grafana on Worker1
  hosts: master
  become: yes
  tasks:
    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Create monitoring namespace
      command: kubectl create namespace monitoring
      ignore_errors: yes

    - name: Create custom values.yaml for nodeSelector
      copy:
        dest: /tmp/prometheus_values.yaml
        content: |
          nodeSelector:
            kubernetes.io/hostname: "worker1"

    - name: Install Prometheus & Grafana on Worker1
      command: >
        helm install prometheus prometheus-community/kube-prometheus-stack
        --namespace monitoring
        --values /tmp/prometheus_values.yaml
